config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'slips/print' => 'slips#print'

  resources :slips

   root 'slips#index'

end

app/models/slip.rb
class Slip < ActiveRecord::Base
  validates_presence_of :value, :from, :city, :date, :signature
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # require './lib/brnumeros/number_portuguese.rb'
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/slips_controller.rb
class SlipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_slip, only: [:show, :edit, :update, :destroy]

  # GET /slips
  # GET /slips.json

  def print
    print_params = params[:print_slips].split(',')
    @print_slips = Slip.find(print_params)
    render :print, :layout => 'print_layout'
  end

  def index
    @slips = Slip.all
    @slip = Slip.new

  end

  # GET /slips/1
  # GET /slips/1.json
  def show
  end

  # GET /slips/new
  def new
    @slip = Slip.new
  end

  # GET /slips/1/edit
  def edit
  end

  # POST /slips
  # POST /slips.json
  def create
    @slip = Slip.new(slip_params)

    respond_to do |format|
      if @slip.save
        # format.html { redirect_to @slip, notice: 'Slip was successfully created.' }
        format.js { }
      else
        # format.html { render :new }
        # format.js { render json: @slip.errors.full_messages, status: :unprocessable_entity }
        # format.js { render :partial => "errors.js.erb", :locals => {:errors => @slip.errors.full_messages} }
        format.js { render :file => "/slips/errors.js.erb", :locals => {:errors => @slip.errors.full_messages} }

      end
    end
  end

  # PATCH/PUT /slips/1
  # PATCH/PUT /slips/1.json
  def update
    respond_to do |format|
      if @slip.update(slip_params)
        format.html { redirect_to @slip, notice: 'Slip was successfully updated.' }
        format.js { }
      else
        format.html { render :edit }
        format.json { render json: @slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slips/1
  # DELETE /slips/1.json
  def destroy
    @slip.destroy
    respond_to do |format|
      format.html { redirect_to slips_url, notice: 'Slip was successfully destroyed.' }
      format.js { }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slip
      @slip = Slip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slip_params
      params.require(:slip).permit(:image, :value, :from, :description, :city, :date, :signature, :cpf, :rg)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slips_helper.rb
module SlipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Receipt" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->  <!-- Material Design fonts -->

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Entrou como <strong><%= current_user.email %></strong>.
            <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->


    </div> <!-- /container -->
    
      <footer class="hidden-print">
        <pre class="fixed-pre">&copy; Thales Miguel 2016</pre>
      </footer>
  </body>
</html>

app/views/layouts/print.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Receipt" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "print", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 print-body">
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/print_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Receipt" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "print", :media => "all" %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag "extenso" %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
</html>

app/views/slips/_form.html.erb
<%= form_for slip, :html => { :class => "myFrom form-horizontal slip", :remote => true}  do |f| %>

  <div class="card">
    <% if slip.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(slip.errors.count, "error") %> prohibited this slip from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% slip.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="card-image">
      <div class="card-form">
        <div class="col-lg-3">
          <%= f.select :image, [['Central', 'centralleiloes.jpg'], ['Recibo', 'recibo.png']], {}, { :class => 'form-control' } %>
        </div>
        <div class="col-lg-6 receiptTitle">
          <label class="receiptTitle">R E C I B O</label>
        </div>
        <div class="col-lg-3">
          <div class="input-group">
            <div class="input-group-addon">R$</div>
            <%= f.text_field :value, :class => 'form-control', :placeholder => 'Valor' %>
          </div>
        </div>
        <%#=f.error_span(:image) %>
      </div>
    </div>

    <div class="card-content">
      <div class="form-group">
        <label class="control-label col-lg-2">Recebemos de </label>
        <div class="col-lg-10">
          <%= f.text_field :from, :class => 'form-control' %>
        </div>
        <%=f.error_span(:from) %>
      </div>
      
      <div class="form-group">
        <label class="control-label col-lg-2">A importancia de</label>
        <div class="col-lg-10">
          <input id="valExtenso" class="form-control" type="text">
        </div>
        <%=f.error_span(:from) %>
      </div>
      
      <div class="form-group">
        <label class="control-label col-lg-2">Proveniente de</label>
        <div class="col-lg-10">
          <%= f.text_area :description, :class => 'form-control', :rows => '4', :'data-limit-rows' => "true" %>
        </div>
        <%=f.error_span(:description) %>
      </div>

      <div class="form-group">
        <span class="col-lg-7"></span>
        <div class="col-lg-3">
          <%= f.text_field :city, :class => 'form-control', :placeholder => 'Cidade', :value => 'Araçatuba' %>
        </div>
        <%=f.error_span(:city) %>
        <div class="col-lg-2">
          <%= f.date_field :date, :class => 'form-control', :value => Time.now.strftime('%Y-%m-%d') %>
        </div>
        <%=f.error_span(:date) %>
      </div>

      <div class="form-group">
        <span class="col-lg-7"></span>
        <div class="col-lg-5">
          <%= f.text_field :signature, :class => 'form-control', :placeholder => 'Assinatura', :value => 'Central Leilões LTDA' %>
        </div>
        <%=f.error_span(:signature) %>
      </div>

      <div class="form-group">
        <span class="col-lg-6"></span>
        <%= f.label :cpf, :class => 'control-label col-lg-1' %>
        <div class="col-lg-2">
          <%= f.text_field :cpf, :class => 'form-control' %>
        </div>
        <%=f.error_span(:cpf) %>

        <%= f.label :rg, :class => 'control-label col-lg-1' %>
        <div class="col-lg-2">
          <%= f.text_field :rg, :class => 'form-control' %>
        </div>
        <%=f.error_span(:rg) %>

      </div>
    </div>

    <div class="card-action">
      <div class="form-group">
        <div id="fromCtrl" class="col-lg-10">
          
          <%= link_to t('.cancel', :default => t("helpers.links.novo")),
            new_slip_path, :class => 'btn btn-default', :remote => true %>



          <%= f.submit nil, :class => 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>

  <% end %>

app/views/slips/_slip.html.erb
<tr id="<%= slip.id %>">
  <td><abbr title= '<%= slip.from %>'> <%= slip.from[0..40] %></abbr></td>
  <td><%= number_to_currency(slip.value) %></td>
  <td><abbr title= '<%= slip.description %>'> <%= slip.description[0..40] %></abbr></td>
  <td><%= slip.city %></td>
  <td><%=l slip.date %></td>
  <td><%= slip.signature %></td>
  <td id="tdCtrl">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_slip_path(slip), :class => 'btn btn-default btn-xs', :remote => true %>

    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                slip_path(slip),
                :remote => true,
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Tem certeza que deseja excluir esse recibo?')) },
                :class => 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/slips/_slip_print.html.erb
<div class="col-xs-12 print-body">
  <div class="col-xs-12 print-header">
    <div class="col-xs-3">
      <%= image_tag(slip.image, :size => "90x90", :id => "slip_image_tag") %>
    </div>
    <div class="col-xs-6 print-receipt">
      <p class="print-receipt">R E C I B O</p>
    </div>
    <div class="col-xs-3">      
      <p><input type="text" class="print-value" id="slip_value<%=slip.id%>" value="R$ <%= slip.value %>" disabled="true"></p> 
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <strong><label class="control-label col-xs-2 print-from">Recebemos de &nbsp</label></strong>
      <div class="col-xs-10 uppercase">
        <strong> <%= slip.from %> </strong>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <strong><label class="control-label col-xs-2">A importancia de </label></strong>
      <div class="col-xs-10">
        <input id="valExtenso<%=slip.id%>" class="form-control print-full-value uppercase" type="text" disabled="true" >
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <strong><label class="control-label">Proveniente de</label></strong>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <div class="print-description">
        <%= slip.description.gsub('&nbsp', 'BOZO') %>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <span class="col-xs-6"></span>
      <div class="col-xs-6 print-city uppercase">
        <%= slip.city %>, <%=l slip.date, :format => :long %>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <span class="col-xs-6"></span>
      <div class="col-xs-6 print-signature uppercase">
        <%= slip.signature %>
      </div>
    </div>
  </div>

  <div class="col-xs-12">
    <div class="form-group">
      <span class="col-xs-6"></span>
      <div class="col-xs-3">
        <label>CPF</label> <%= slip.cpf %>
      </div>
      <div class="col-xs-3">
        <label>RG</label> <%= slip.rg %>
      </div>
    </div>
  </div>
</div>

<script>
  $('document').ready(function(){

    function getQueryVariable(variable){
      var query = window.location.search.substring(1);
      var vars = query.split("&");
      for (var i=0;i<vars.length;i++) {
        var pair = vars[i].split("=");
        if(pair[0] == variable){return pair[1];}
       }
       return(false);
    }

    var slips = getQueryVariable("print_slips").split(","); 
    slips.forEach(function printExtenso(id){
      var value = $("#slip_value" + id).val();
      $("#valExtenso" + id).val(value.extenso('cur'));
    
    });

    // var value = $("#slip_value6").val();
    // $("#valExtenso6").val(value.extenso('cur'));
    
    // console.log(slips);
    
    // var value = $("#slip_value").val();
    // $("#valExtenso").val(value.extenso('cur'));
    // alert(value.extenso('cur'));
  });
</script>

app/views/slips/create.js.erb
$("<%= j render partial: 'slip', locals: { slip: @slip } %>").addClass("animated fadeIn").appendTo('tbody#slips_list');

$('#slip_value').val('');
$('#slip_from').val('');
$('#slip_description').val('');
$('#slip_city').val('Araçatuba');
$('#slip_date').val("<%= Time.now().strftime('%Y-%m-%d') %>");
$('#slip_signature').val('Central Leilões LTDA');
$('#slip_cpf').val('');
$('#slip_rg').val('');

app/views/slips/destroy.js.erb
$("tr#<%= @slip.id %>").removeClass('animated');
$("tr#<%= @slip.id %>").fadeOut();

app/views/slips/edit.html.erb
<%- model_class = Slip -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/slips/edit.js.erb
$('div#renderForm').remove();
$("<div id='renderForm'> <%= j render partial: 'form', locals: { slip: Slip.find( params[:id] )} %> </div").appendTo('div#receiptForm');

app/views/slips/errors.js.erb
var e = "";
<% errors.each do |error| %>
  e += '<%= error %>' + '\n\n';
<% end %>
alert(e);

app/views/slips/index.html.erb
<div class="receiptForm" id="receiptForm">
  <%#= render :partial => "form" %>
  <div id="renderForm">
    <%= render :partial => "form", :locals => {:slip => @slip} %>
  </div>
</div>

<div class="card">
  <div class="card-content">
    <%= link_to slips_print_path(), :id => "printButton", :class => 'btn btn-primary btn-lg disabled', :target => "_blank" do %>
      <span class="glyphicon glyphicon-print"></span> Imprimir   
    <% end %>
    
    <%- model_class = Slip -%>
    <table class="table table-hover" id="dataTable">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:recebemos_de) %></th>
          <th><%= model_class.human_attribute_name(:valor) %></th>
          <th><%= model_class.human_attribute_name(:proveniente_de) %></th>
          <th><%= model_class.human_attribute_name(:cidate) %></th>
          <th><%= model_class.human_attribute_name(:data) %></th>
          <th><%= model_class.human_attribute_name(:assinatura) %></th>
          <th><%=t '.actions', :default => t("helpers.ações") %></th>
        </tr>
      </thead>
      <tbody id="slips_list">
        <%= render @slips %>
      </tbody>
    </table>
  </div>
</div>

app/views/slips/new.html.erb
<%- model_class = Slip -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/slips/new.js.erb
$('div#renderForm').remove();
$("<div id='renderForm'> <%= j render partial: 'form', :locals => {:slip => @slip} %> </div").appendTo('div#receiptForm');

app/views/slips/print.html.erb
<% @print_slips.each do |slip| %>
  <%= render :partial => "slip_print", :locals => {:slip => slip} %>
<% end %>

app/views/slips/show.html.erb
<%- model_class = Slip -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @slip.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @slip.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:from) %>:</strong></dt>
  <dd><%= @slip.from %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @slip.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @slip.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:signature) %>:</strong></dt>
  <dd><%= @slip.signature %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @slip.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rg) %>:</strong></dt>
  <dd><%= @slip.rg %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              slips_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_slip_path(@slip), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              slip_path(@slip),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/slips/update.js.erb
$('tr#<%= @slip.id %>').replaceWith("<%= escape_javascript(render partial: 'slip', locals: { slip: @slip }) %>");